[package]
name = "sunray"
version = "0.1.0"
edition = "2021"
license = "AGPL-3.0-only"
description = "feature-rich hardware ray-tracing library"
repository = "https://github.com/Kalsifer-742/sunray.git"
readme = "README.md"
keywords = ["gamedev", "graphics"]
categories = ["graphics", "hardware-support", "game-development"]

[dependencies]
vulkano = "0.35.1"
vulkano-shaders = "0.35.0"
winit = "0.30.9"

[profile.dev]
opt-level = 1 
